#!/usr/bin/env bash

set -e

nix run nix-darwin -- switch --flake .
# current=$(nixos-rebuild list-generations | grep current)
# git commit -am "$current"
# notify-send -e "NixOS Rebuilt OK" --icon=software-update-available
