# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/aec45494-431c-4c3a-8f13-2271240fd25b";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/FEB0-2C27";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/media" = {
    device = "192.168.69.11:/data/media";
    fsType = "nfs";
    options = [
      "nfsvers=4"
      "hard"
      "noauto"
      "x-systemd.automount"
      "x-systemd.mount-timeout=90"
      "noatime"
    ];
  };

  fileSystems."/backups" = {
    device = "192.168.69.11:/data/backups";
    fsType = "nfs";
    options = [
      "nfsvers=4"
      "hard"
      "noauto"
      "x-systemd.automount"
      "x-systemd.mount-timeout=90"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/e89a9815-6fb3-44b8-8a8f-3c10b140b4e5"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
