# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/d3b2fa70-7701-43f4-b9aa-064f0e9d63da";

  fileSystems."/home" =
    { device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/swap" =
    { device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5DBB-680C";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/mnt/nas/backups" = {
    device = "192.168.69.11:/backups";
    fsType = "nfs";
    options = [
      "nfsvers=4"
      "hard"
      "noauto"
      "x-systemd.automount"
      "x-systemd.mount-timeout=90"
    ];
  };

  fileSystems."/mnt/nas/trond" = {
    device = "192.168.69.11:/trond";
    fsType = "nfs";
    options = [
      "nfsvers=4"
      "hard"
      "noauto"
      "x-systemd.automount"
      "x-systemd.mount-timeout=90"
      "noatime"
    ];
  };

  fileSystems."/mnt/nas/media" = {
    device = "192.168.69.11:/media";
    fsType = "nfs";
    options = [
      "nfsvers=4"
      "hard"
      "noauto"
      "x-systemd.automount"
      "x-systemd.mount-timeout=90"
      "noatime"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
